name: sidequests
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  sqflite: ^2.3.2
  path: ^1.8.3
  uuid: ^4.2.2
  google_fonts: ^6.1.0
  dart_openai: ^4.0.0
  flutter_spinkit: ^5.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/backend/.env
